# Generated by Django 4.0.3 on 2022-03-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('EX', 'Excerpt'), ('WR', 'Writing'), ('LY', 'Lyrics')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published'), ('AR', 'Archived')], default=0, max_length=2),
        ),
    ]
