# Generated by Django 4.0.3 on 2022-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_fragment_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='content',
        ),
        migrations.AddField(
            model_name='fragment',
            name='chinese_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='english_content',
            field=models.TextField(blank=True),
        ),
    ]
