# Generated by Django 4.0.3 on 2022-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_author_fragment_english_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='chinese_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='english_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
