# Generated by Django 4.0.3 on 2022-06-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_fragment_chinese_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='image_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
