# Generated by Django 4.0.3 on 2022-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_fragment_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragment',
            old_name='origin',
            new_name='english_origin',
        ),
        migrations.AddField(
            model_name='fragment',
            name='chinese_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
