# Generated by Django 4.0.3 on 2022-03-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_originally_written_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-originally_written_on']},
        ),
    ]
