# Generated by Django 4.0.3 on 2022-05-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('originally_written_on', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published'), ('AR', 'Archived')], default='DR', max_length=2)),
                ('category', models.CharField(choices=[('EX', 'Excerpt'), ('WR', 'Writing')], default='WR', max_length=2)),
                ('language', models.CharField(choices=[('EN', 'English'), ('CH', 'Chinese'), ('BO', 'Both')], default='CH', max_length=2)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-originally_written_on'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
